### ISSUE TITLE
No section: 'CODE_GENERATION'

### ISSUE THREAD

**Issue by dpo** [PythonOptimizers/HSL.py#5]
```
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    use_cython = hsl_config.getboolean('CODE_GENERATION', 'use_cython')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'CODE_GENERATION'
```

**Comment by glkarpov** [comment]
> I added
> 
> ```
> [CODE_GENERATION]
> use_cython = true
> use_debug_symbols = false
> log_name = generator
> log_level = DEBUG
> console_log_level = DEBUG
> file_log_level = DEBUG
> ```
> 
> to `site.cfg` and ran `python generate_code.py` followed by `python setup.py install`. That compiled. But there are no tests.
> 
> Users will never use this if it's not obvious.

Where is `site.cfg`?

**Comment by dpo** [comment]
We need maintainers. I haven’t touched this in years and don’t have the time unfortunately.
